### PR TITLE
Remove drawables for ic_launcher don't abort the build on lint errors.

### PR DESCRIPTION
**Pull request by kingargyle**
Removes the unnecessary drawables that aren't used by the library.  This prevents compilation issues when other AARs are accidently including them as well.

Also set the build not to abort on lint errors.

### CODE REVIEW

**Comment by TonicArtos** [comment]
Thank you for the pull request. I'd just like some clarification on why you want to set AbortOnError to false.

**Comment by kingargyle** [comment]
It was just so I can get a clean compile.  You can leave it as default if you want.

**Comment by TonicArtos** [comment]
Merged by patch in c5ada44.

**Comment by kingargyle** [comment]
No problem all is well. Thanks for the quick merge.

**Comment by TonicArtos** [comment]
:)

**Pull request closed without merging**
